USE CODEGNAN;
CREATE TABLE STUDENT_DATA(
    STUDENT_NAME VARCHAR (50) NOT NULL,
    STUDENT_SUBJECT VARCHAR (10) NOT NULL,
    MARKS INT DEFAULT 0
 );
DESC STUDENT_DATA;
INSERT INTO STUDENT_DATA VALUES(1,"SAI","ENGLISH",90),(1,"SAI","MATHS",80),(1,"SAI","SOCIAL",70);
SELECT * FROM STUDENT_DATA;
INSERT INTO STUDENT_DATA VALUES(2,"VARUN","ENGLISH",99),(2,"VARUN","MATHS",99),(2,"VARUN","SOCIAL",99);
INSERT INTO STUDENT_DATA VALUES(3,"TARUN","ENGLISH",99),(3,"TARUN","MATHS",9),(3,"TARUN","SOCIAL",9);
INSERT INTO STUDENT_DATA VALUES(4,"NIKHIL","ENGLISH",9),(4,"NIKHIL","MATHS",100),(4,"NIKHIL","SOCIAL",9);
INSERT INTO STUDENT_DATA VALUES(5,"CHAITU","ENGLISH",30),(5,"CHAITU","MATHS",30),(5,"CHAITU","SOCIAL",100);
INSERT INTO STUDENT_DATA VALUES(6,"KRISHNA","ENGLISH",100),(6,"KRISHNA","MATHS",30),(6,"KRISHNA","SOCIAL",40);
SELECT COUNT(ID) FROM STUDENT_DATA;
SELECT SUM(MARKS) FROM STUDENT_DATA;
SELECT MAX(MARKS) FROM STUDENT_DATA;
SELECT MIN(MARKS) FROM STUDENT_DATA;
SELECT AVG(MARKS) FROM STUDENT_DATA;
-- I NEED TOTAL MARKS RECORDS FRO EACH STUDENT
SELECT ID,SUM(MARKS) FROM STUDENT_DATA GROUP BY ID;
SELECT ID,SUM(MARKS) AS TOTAL_MARKS FROM STUDENT_DATA GROUP BY ID;
SELECT ID,MARKS AS ENGLISH_MARKS FROM STUDENT_DATA WHERE STUDENT_SUBJECT="ENGLISH";
SELECT ID,STUDENT_NAME,SUM(MARKS) AS TOTAL_MARKS FROM STUDENT_DATA GROUP BY ID,STUDENT_NAME;
SELECT ID,STUDENT_NAME,SUM(MARKS) AS TOTAL_MARKS FROM STUDENT_DATA GROUP BY ID,STUDENT_NAME HAVING TOTAL_MARKS > 150;
SELECT ID,STUDENT_NAME,SUM(MARKS) AS TOTAL_MARKS FROM STUDENT_DATA GROUP BY ID,STUDENT_NAME HAVING TOTAL_MARKS > 120 ORDER BY  TOTAL_MARKS ASC;
CREATE TABLE FINAL_MARKS( ID INT PRIMARY KEY, STUDENT_NAME VARCHAR (100), STUDENT_MARKS INT);
INSERT INTO FINAL_MARKS SELECT ID,STUDENT_NAME,SUM(MARKS) AS TOTAL_MARKS FROM STUDENT_DATA GROUP BY ID,STUDENT_NAME;
SELECT * FROM FINAL_MARKS;