USE CODEGNAN;
CREATE TABLE STUDENT123(
     ID INT,
     SNAME VARCHAR (50)
);
INSERT INTO STUDENT123 VALUES (1,"SAI 1"),(2,"SAI 2"),(3,"SAI 3"),(4,"SAI 4");
SELECT * FROM STUDENT123;
CREATE TABLE COURSE123(
     CID INT,
     CNAME VARCHAR (50)
);
INSERT INTO COURSE123 VALUES(1,"ECE"),(2,"EEE"),(1,"CSE"),(3,"ABC");
INSERT INTO COURSE123 VALUES(5,"SAI 5");
SELECT * FROM COURSE123;
-- INNER JOIN 
SELECT ID,SNAME,CNAME FROM STUDENT123
INNER JOIN COURSE123
ON STUDENT123.ID =COURSE123.CID;

-- LEFT JOIN
SELECT ID,SNAME,CNAME FROM STUDENT123
LEFT JOIN COURSE123
ON STUDENT123.ID = COURSE123.CID;

-- RIGTH JOIN
SELECT ID, SNAME ,CNAME FROM STUDENT123
RIGHT JOIN COURSE123
ON STUDENT123.ID = COURSE123.CID;

-- FULL OUTER JOIN
SELECT ID,SNAME,CNAME FROM STUDENT123
LEFT JOIN COURSE123
ON STUDENT123.ID = COURSE123.CID
UNION
SELECT ID,SNAME,CNAME FROM STUDENT123
RIGHT JOIN COURSE123
ON STUDENT123.ID = COURSE123.CID;

CREATE TABLE CLR (
     COLOR1 VARCHAR (10),
     CNAME VARCHAR (10),
     COLOR2 VARCHAR (10)
);
INSERT INTO CLR VALUES("BLUE","JOHN","RED"),("GREEN","ALEX","BLUE"),("RED","SIMON","GREEN");
SELECT * FROM CLR;
SELECT A.CNAME AS NAME,B.CNAME AS SECRECT_SANTA
FROM CLR AS A, CLR AS B
WHERE A.COLOR1=B.COLOR2;
CREATE TABLE HAIRSTYLE(
     NAMEE VARCHAR(50)
);
INSERT INTO HAIRSTYLE VALUES ("STRAIGHT"),("CURLY");
SELECT * FROM HAIRSTYLE;
CREATE TABLE HAIRTYPE(
     UNAME VARCHAR(3)
);
INSERT INTO HAIRTYPE VALUES ("A"),("B"),("C"),("D");
SELECT * FROM HAIRTYPE;
SELECT  UNAME,NAMEE FROM HAIRSTYLE
CROSS JOIN 
HAIRTYPE
LIMIT 5;
