 USE CODEGNAN;
CREATE TABLE EMPS(ID INT ,EMPNAME VARCHAR(50),CITY VARCHAR (20)); 
INSERT INTO EMPS VALUES (1,"SAI","LONDON"),(2,"VARUN","LONDEN"),(3,"TARUN","INDIA"),(4,"DEEPS","INDIA");
SELECT * FROM EMPS;

-- -------------CONCAT
SELECT CONCAT ("SAI"," ","VARDHAN ") AS FULLNAME;
SELECT CONCAT (EMPNAME," PLACE IS ",CITY) AS DETAILS FROM EMPS;

-- ------------CONCAT_WS
 SELECT CONCAT_WS (",","SAI","VARUN","TARUN","DEEPS") AS NAMES;
SELECT CONCAT_WS (", ",EMPNAME,CITY) AS DETAILS FROM EMPS;

-- ------------LOWER  AND UPPER 
SELECT UPPER("Hello") AS CAPITAL;
SELECT LOWER("Hello") AS LOWER;
SELECT EMPNAME,UPPER(EMPNAME) AS CAPTIAL ,CITY , LOWER (CITY) AS SMALL FROM EMPS; 

-- -----------LENGHT
SELECT LENGTH("HELLO") AS LENGHT;
SELECT CHAR_LENGTH("HELLO") AS CAHRLENGHT;
SELECT ID , LENGTH(EMPNAME)AS LENGTH , CHAR_LENGTH(EMPNAME ) AS NAMECHARLENGTH FROM EMPS;

-- ---------SUBSTRING 
SELECT SUBSTRING("VENKATESH",6);  --    TESH
SELECT SUBSTRING("VENKATESH",2,6);   -- ENKATE
SELECT EMPNAME,SUBSTRING(EMPNAME,2,5) AS SUBSTRR FROM EMPS;

--  -------------------REVERSE
SELECT REVERSE ("SAI") AS REV;
SELECT ID,EMPNAME,REVERSE(EMPNAME) AS REVNAME FROM EMPS;

-- ----------REPLACE
SELECT REPLACE ("SAI VARDHAN","SAI","I") AS REPLACED_STRING;
SELECT ID,EMPNAME,REPLACE (EMPNAME,"SAI","I") AS RE_STRING FROM EMPS;

-- ------------LIKE(%)
SELECT "SAI VARDHAN" LIKE "%VARDHAN" AS XYZ; -- 1
SELECT "SAI VARDHAN" LIKE "%VARDHANNN" AS XYZ;  -- 0
SELECT "SAI VARDHAN" LIKE "S_I VARDHAN" AS XYZ;    -- 1
SELECT "SAI VARDHAN" LIKE "VARDHAN%" AS XYZ;   -- 0
SELECT * FROM EMPS WHERE CITY LIKE "%IA" ;
SELECT * FROM EMPS WHERE CITY LIKE "LOND_N";



